# Generated by Django 4.0.3 on 2022-05-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255, unique=True)),
                ('nit_empresa', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obligaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obligacion', models.CharField(max_length=255)),
                ('periodicidad', models.CharField(max_length=255)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('valor', models.CharField(max_length=255)),
                ('id_obligacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.obligaciones')),
            ],
        ),
    ]
