# Generated by Django 4.0.4 on 2022-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligaciones',
            name='periocidad',
            field=models.CharField(default='s', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
