# Generated by Django 4.0.3 on 2022-05-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligaciones',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='obligaciones',
            name='nombre_empresa',
        ),
    ]
