# Generated by Django 4.0.4 on 2022-04-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_obligaciones_periocidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obligaciones',
            old_name='periocidad',
            new_name='periodicidad',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor',
        ),
    ]
